# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ostorlab/agent/message/proto/v4/asset/asset.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1ostorlab/agent/message/proto/v4/asset/asset.proto\x12%ostorlab.agent.message.proto.v4.asset\"\xdb\x01\n\x07Message\x12\x10\n\x08selector\x18\x01 \x01(\t\x12\x16\n\x0eschema_version\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\x12\x14\n\x0c\x63ontent_type\x18\x04 \x01(\t\x12N\n\x08metadata\x18\x05 \x03(\x0b\x32<.ostorlab.agent.message.proto.v4.asset.Message.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ostorlab.agent.message.proto.v4.asset.asset_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGE_METADATAENTRY._options = None
  _MESSAGE_METADATAENTRY._serialized_options = b'8\001'
  _MESSAGE._serialized_start=93
  _MESSAGE._serialized_end=312
  _MESSAGE_METADATAENTRY._serialized_start=265
  _MESSAGE_METADATAENTRY._serialized_end=312
# @@protoc_insertion_point(module_scope)
